development:
  adapter: postgresql
  encoding: unicode
  database: pinteresting_development
  pool: 5
  username: ccandelora
  password: Bytes1010

test:
  adapter: postgresql
  encoding: unicode
  database: pinteresting_test
  pool: 5
  username: ccandelora
  password: Bytes1010